version: '3.10'

services:
  app1:
    image: microservice:0.0.1
    build: .
    ports:
      - "8000:8000"
    environment:
      - TRACING_HOST=jaeger
      - TRACING_PORT=6831

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411